<?php
/**
 * Message_Business_ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Message_Business_Configuration;
use \Swagger\Client\Message_Business_ApiClient;
use \Swagger\Client\Message_Business_ApiException;
use \Swagger\Client\Message_Business_ObjectSerializer;

/**
 * Message_Business_ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Message_Business_ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for contactDeleteContactByKey
     *
     * Supprimer d\u00E9finitivement un contact
     *
     */
    public function test_contactDeleteContactByKey() {

    }
    
    /**
     * Test case for contactGetContacHistory
     *
     * Obtenir la liste des activit\u00E9s d'un contact
     *
     */
    public function test_contactGetContacHistory() {

    }
    
    /**
     * Test case for contactGetContactAttributeIdKey
     *
     * Obtenir une valeur sp\u00E9cifique avec la cl\u00E9 d'unicit\u00E9
     *
     */
    public function test_contactGetContactAttributeIdKey() {

    }
    
    /**
     * Test case for contactGetContactAttributeKey
     *
     * Obtenir la liste des informations d'un contact
     *
     */
    public function test_contactGetContactAttributeKey() {

    }
    
    /**
     * Test case for contactPostContacHistory
     *
     * Ajouter une activit\u00E9 \u00E0 un contact suite \u00E0 une op\u00E9ration
     *
     */
    public function test_contactPostContacHistory() {

    }
    
    /**
     * Test case for contactPostContactAttributeKey
     *
     * Cr\u00E9er ou mettre \u00E0 jour les informations d'un contact
     *
     */
    public function test_contactPostContactAttributeKey() {

    }
    
    /**
     * Test case for contactPutContactAttributeKey
     *
     * Mettre \u00E0 jour des informations du contact
     *
     */
    public function test_contactPutContactAttributeKey() {

    }
    
}
