<?php
/**
 * Message_Business_ContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Message_Business_Configuration;
use \Swagger\Client\Message_Business_ApiClient;
use \Swagger\Client\Message_Business_ApiException;
use \Swagger\Client\Message_Business_ObjectSerializer;

/**
 * Message_Business_ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Message_Business_ContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for contactsDeleteDelete
     *
     * Supprimer d\u00E9finitivement une pr\u00E9c\u00E9dente purge
     *
     */
    public function test_contactsDeleteDelete() {

    }
    
    /**
     * Test case for contactsDeleteExport
     *
     * Supprimer d\u00E9finitivement un export
     *
     */
    public function test_contactsDeleteExport() {

    }
    
    /**
     * Test case for contactsDeleteImport
     *
     * Supprimer d\u00E9finitivement les information d'un pr\u00E9cedent import
     *
     */
    public function test_contactsDeleteImport() {

    }
    
    /**
     * Test case for contactsGetDelete
     *
     * Obtenir les informations d'une pr\u00E9c\u00E9dente purge
     *
     */
    public function test_contactsGetDelete() {

    }
    
    /**
     * Test case for contactsGetDeleteList
     *
     * Obtenir la liste des pr\u00E9c\u00E9dentes purges
     *
     */
    public function test_contactsGetDeleteList() {

    }
    
    /**
     * Test case for contactsGetExport
     *
     * Obtenir les informations d'un pr\u00E9c\u00E9dent export
     *
     */
    public function test_contactsGetExport() {

    }
    
    /**
     * Test case for contactsGetExportList
     *
     * Obtenir la liste des pr\u00E9c\u00E9dents exports
     *
     */
    public function test_contactsGetExportList() {

    }
    
    /**
     * Test case for contactsGetFileDelete
     *
     * T\u00E9l\u00E9charger le fichier d'archive de la purge
     *
     */
    public function test_contactsGetFileDelete() {

    }
    
    /**
     * Test case for contactsGetFileExport
     *
     * T\u00E9l\u00E9charger le fichier d'archive de l'export
     *
     */
    public function test_contactsGetFileExport() {

    }
    
    /**
     * Test case for contactsGetFileImport
     *
     * T\u00E9l\u00E9charger le fichier d'archive d'un import
     *
     */
    public function test_contactsGetFileImport() {

    }
    
    /**
     * Test case for contactsGetImport
     *
     * Obtenir les informations d'un pr\u00E9c\u00E9dent import
     *
     */
    public function test_contactsGetImport() {

    }
    
    /**
     * Test case for contactsGetImportList
     *
     * Obtenir la liste des pr\u00E9c\u00E9dents imports
     *
     */
    public function test_contactsGetImportList() {

    }
    
    /**
     * Test case for contactsPostDeleteOperation
     *
     * Effectuer une purge \u00E0 partir d'un fichier
     *
     */
    public function test_contactsPostDeleteOperation() {

    }
    
    /**
     * Test case for contactsPostExportOperation
     *
     * Lancer un nouvel export de la base de contact
     *
     */
    public function test_contactsPostExportOperation() {

    }
    
    /**
     * Test case for contactsPostImportOperation
     *
     * Effectuer un nouvel import dans la base de contacts
     *
     */
    public function test_contactsPostImportOperation() {

    }
    
    /**
     * Test case for contactsPutContactAttributeKey
     *
     * Mettre \u00E0 jour des informations de contacts (jusqu'\u00E0 500)
     *
     */
    public function test_contactsPutContactAttributeKey() {

    }
    
}
